PhotoService/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
]

# MEDIA_ROOTを公開する（アクセス可能にする）
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('users/<int:pk>/', views.users_detail, name='users_detail'),
    path('photos/new/', views.photos_new, name='photos_new'),
    path('photos/<int:pk>/', views.photos_detail, name='photos_detail'),
    path('photos/<int:pk>/delete/', views.photos_delete, name='photos_delete'),
    path('photos/<str:category>/', views.photos_category, name='photos_category'),
    path('icon_new/', views.icon_new, name='icon_new'),
]

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>写真投稿サイト</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>
<header>
    <div class="container">
        <h1><a href="{% url 'app:index' %}">写真投稿サイト</a></h1>
        <div class="header-menu">
            <a href="{% url 'app:photos_new' %}">投稿</a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'app:users_detail' request.user.id %}">マイページ</a>
            <a href="{% url 'accounts:logout' %}">ログアウト</a>
            {% else %}
            <a href="{% url 'accounts:register' %}">新規登録</a>
            <a href="{% url 'accounts:login' %}">ログイン</a>
            {% endif %}
        </div>
    </div>
</header>

<div class="container">
    {% for message in messages %}
    <p class="message-success">{{ message }}</p>
    {% endfor %}
    {% block content %}{% endblock %}
</div>

</body>

</html>

app/templates/app/icon_new.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>

<form action="{% url 'app:icon_new' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">保存</button>
</form>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}

<div id="index">

    <h2>トップページ</h2>

    {% if category %}
        <h2>カテゴリー：{{ category.title }} の検索結果</h2>
    {% endif %}

    {% include 'app/photos_list.html' %}

</div>

{% endblock %}

app/templates/app/photos_detail.html
{% extends 'app/base.html' %}

{% block content %}

<div class="photo-detail">

    <img src="{{ photo.image.url }}" class="photo-img">
        <a href="{% url 'app:users_detail' photo.user.id %}">
            <div class="photo-info">
                <div class="icon-and-name">
                    <p><img src="{{ photo.user.icon.image.url }}" onerror="this.onerror=null;this.src='/media/icons/default.jpg'" class="icon-img"></p>
                    <p>{{ photo.user.username }}</p>
                </div>
            </div>
        </a>

    <h2>{{ photo.title }}</h2>
    <p>{{ photo.description }}</p>

    <div id="comments">
        {% for comment in comments %}
        <div>
            <div class="icon-and-name">
                <p><img src="{{ comment.user.icon.image.url }}" onerror="this.onerror=null;this.src='/media/icons/default.jpg'" class="icon-img"></p>
                <p>{{ comment.user }}</p>
            </div>
            <p class="comment-text">{{ comment.text }}</p>
        </div>
        {% endfor %}
    </div>

    <!-- 削除ボタン　-->
    {% if request.user == photo.user %}
        <form method="post" action="{% url 'app:photos_delete' photo.id %}">{% csrf_token %}
            <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
        </form>
    {% else %}
        <form id="comments-add" action="{% url 'app:photos_detail' photo.id %}" method="POST">
            <p>コメント:<p>
            {% csrf_token %}
            {{ form.text }}
            <button type="submit" class="btn">送信</button>
        </form>
    {% endif %}

</div>
{% endblock %}

app/templates/app/photos_list.html
<div class="photo-container">
{% for photo in photos %}
    <div class="photo">
        <a href="{% url 'app:photos_detail' photo.id %}">
            <img src="{{ photo.image.url }}" class="photo-img">
        </a>
        <div class="photo-info">
            <a href="{% url 'app:photos_category' category=photo.category %}" class="category">{{ photo.category }}</a>
            <a href="{% url 'app:users_detail' photo.user.id %}">
                <div class="icon-and-name">
                    <p><img src="{{ photo.user.icon.image.url }}" onerror="this.onerror=null;this.src='/media/icons/default.jpg'" class="icon-img"></p>
                    <p>{{ photo.user }}</p>
                </div>
            </a>
        </div>
    </div>
{% endfor %}
</div>

app/templates/app/photos_new.html
{% extends 'app/base.html' %}

{% block content %}

<div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>

<form action="{% url 'app:photos_new' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
        <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>コメント</th>
            <td>{{ form.description}}</td>
        </tr>
        <tr>
            <th>画像</th>
            <td>{{ form.image }}</td>
        </tr>
        <tr>
            <th>カテゴリー</th>
            <td>{{ form.category }}</td>
        </tr>
    </table>
    <button type="submit" class="btn">保存</button>
</form>

{% endblock %}

app/templates/app/users_detail.html
{% extends 'app/base.html' %}

{% block content %}

<div id="user_detail">

    <div class="icon-and-name">
        {% if user == request.user %}
        <a href="{% url 'app:icon_new' %}">
            <p><img src="{{ user.icon.image.url }}" class="icon-img"></p>
        </a>
        {% else  %}
            <p><img src="{{ user.icon.image.url }}" class="icon-img"></p>
        {% endif %}

        <p class="user-name">
            {{ user.username }}
        </p>
    </div>

    {% if photos.count != 0 %}
        <p>投稿<strong>{{ photos.count }}</strong>件</p>
    {% else %}
        {% if user == request.user %}
            <p>初めての投稿をしてみましょう！</p>
        {% else %}
            <p>@{{ user.username }}さんはまだ投稿していません。</p>
        {% endif %}
    {% endif %}

</div>
{% include 'app/photos_list.html' %}

{% endblock %}